linters:
  enable:
    - errcheck
    - gocritic
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
