linters:
  enable:
    - copyloopvar
    - errcheck
    - gocritic
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
