---
version: 2
project_name: gotagger
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  - binary: gotagger
    main: ./cmd/gotagger
    ldflags: |
      -X main.BuildDate={{.Env.BUILDDATE}}
      -X main.Commit={{.Env.COMMIT}}
      -X main.AppVersion={{.Env.VERSION}}
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: "386"
archives:
  - format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{.Env.VERSION}}-SNAPSHOT"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
