---
name: actionlint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Lint with actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d
