---
name: actionlint

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Lint with actionlint
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e
