---
name: Build

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  build:
    name: Build and test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [stable, oldstable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version: ${{ matrix.go_version }}

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: make test
